theme: jekyll-theme-minimal
title: Sergio Catalan Portfolio
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jemoji
  - jekyll-remote-theme
description: This is my personal portfolio, I hope you like it!
